package com.orig.gls.jpa;
// Generated May 25, 2016 10:46:27 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name="CATEGORIES"
    ,schema="GLS"
)
public class Categories  implements java.io.Serializable {


     private int categoryid;
     private String bankId;
     private String bocreatedby;
     private Date bodatecreated;
     private Date bodatemodified;
     private String bomodifiedby;
     private String categorycode;
     private String categorytype;
     private String categoryvalue;

    public Categories() {
    }

    public Categories(String bankId, String bocreatedby, Date bodatecreated, Date bodatemodified, String bomodifiedby, String categorycode, String categorytype, String categoryvalue) {
       this.bankId = bankId;
       this.bocreatedby = bocreatedby;
       this.bodatecreated = bodatecreated;
       this.bodatemodified = bodatemodified;
       this.bomodifiedby = bomodifiedby;
       this.categorycode = categorycode;
       this.categorytype = categorytype;
       this.categoryvalue = categoryvalue;
    }
   
     @Id @GeneratedValue

    
    @Column(name="CATEGORYID", unique=true, nullable=false, precision=10, scale=0)
    public int getCategoryid() {
        return this.categoryid;
    }
    
    public void setCategoryid(int categoryid) {
        this.categoryid = categoryid;
    }

    
    @Column(name="BANK_ID", nullable=false, length=8)
    public String getBankId() {
        return this.bankId;
    }
    
    public void setBankId(String bankId) {
        this.bankId = bankId;
    }

    
    @Column(name="BOCREATEDBY", nullable=false, length=30)
    public String getBocreatedby() {
        return this.bocreatedby;
    }
    
    public void setBocreatedby(String bocreatedby) {
        this.bocreatedby = bocreatedby;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="BODATECREATED", nullable=false, length=7)
    public Date getBodatecreated() {
        return this.bodatecreated;
    }
    
    public void setBodatecreated(Date bodatecreated) {
        this.bodatecreated = bodatecreated;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="BODATEMODIFIED", nullable=false, length=7)
    public Date getBodatemodified() {
        return this.bodatemodified;
    }
    
    public void setBodatemodified(Date bodatemodified) {
        this.bodatemodified = bodatemodified;
    }

    
    @Column(name="BOMODIFIEDBY", nullable=false)
    public String getBomodifiedby() {
        return this.bomodifiedby;
    }
    
    public void setBomodifiedby(String bomodifiedby) {
        this.bomodifiedby = bomodifiedby;
    }

    
    @Column(name="CATEGORYCODE", nullable=false, length=50)
    public String getCategorycode() {
        return this.categorycode;
    }
    
    public void setCategorycode(String categorycode) {
        this.categorycode = categorycode;
    }

    
    @Column(name="CATEGORYTYPE", nullable=false, length=30)
    public String getCategorytype() {
        return this.categorytype;
    }
    
    public void setCategorytype(String categorytype) {
        this.categorytype = categorytype;
    }

    
    @Column(name="CATEGORYVALUE", nullable=false, length=200)
    public String getCategoryvalue() {
        return this.categoryvalue;
    }
    
    public void setCategoryvalue(String categoryvalue) {
        this.categoryvalue = categoryvalue;
    }




}


