package com.orig.gls.jpa;
// Generated May 25, 2016 10:46:27 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GroupsTable generated by hbm2java
 */
@Entity
@Table(name="GROUPS_TABLE"
    ,schema="GLS"
)
public class GroupsTable  implements java.io.Serializable {


     private int groupId;
     private String bankId;
     private String branchName;
     private String countryCode;
     private String delFlg;
     private Date firstMeetDate;
     private Date formationDate;
     private String gpChair;
     private String gpRegion;
     private String gpSecretary;
     private String gpStatus;
     private String gpStatusCode;
     private String gpTreasurer;
     private String groupAddress;
     private String groupCenter;
     private String groupCode;
     private double groupLoans;
     private String groupName;
     private String groupPhone;
     private String groupVillage;
     private String grpMgrId;
     private String grpRegNo;
     private Date lchgDate;
     private String lchgUserId;
     private int loanAccounts;
     private int maxAllowedMembers;
     private int maxAllowedSubGrps;
     private String meetFrequency;
     private String meetPlace;
     private String meetTime;
     private int noOfMembers;
     private int noOfSubGrps;
     private Date nxtMeetDate;
     private double outstandingBal;
     private Date rcreTime;
     private String rcreUserId;
     private int savingAccounts;
     private double savingsAmt;
     private int solId;

    public GroupsTable() {
    }

	
    public GroupsTable(String bankId, String branchName, String countryCode, String delFlg, Date firstMeetDate, Date formationDate, String gpRegion, String gpStatus, String gpStatusCode, String groupAddress, String groupCenter, String groupCode, double groupLoans, String groupName, String groupPhone, String groupVillage, String grpMgrId, String grpRegNo, Date lchgDate, String lchgUserId, int loanAccounts, int maxAllowedMembers, int maxAllowedSubGrps, String meetFrequency, String meetPlace, int noOfMembers, int noOfSubGrps, Date nxtMeetDate, double outstandingBal, Date rcreTime, String rcreUserId, int savingAccounts, double savingsAmt, int solId) {
        this.bankId = bankId;
        this.branchName = branchName;
        this.countryCode = countryCode;
        this.delFlg = delFlg;
        this.firstMeetDate = firstMeetDate;
        this.formationDate = formationDate;
        this.gpRegion = gpRegion;
        this.gpStatus = gpStatus;
        this.gpStatusCode = gpStatusCode;
        this.groupAddress = groupAddress;
        this.groupCenter = groupCenter;
        this.groupCode = groupCode;
        this.groupLoans = groupLoans;
        this.groupName = groupName;
        this.groupPhone = groupPhone;
        this.groupVillage = groupVillage;
        this.grpMgrId = grpMgrId;
        this.grpRegNo = grpRegNo;
        this.lchgDate = lchgDate;
        this.lchgUserId = lchgUserId;
        this.loanAccounts = loanAccounts;
        this.maxAllowedMembers = maxAllowedMembers;
        this.maxAllowedSubGrps = maxAllowedSubGrps;
        this.meetFrequency = meetFrequency;
        this.meetPlace = meetPlace;
        this.noOfMembers = noOfMembers;
        this.noOfSubGrps = noOfSubGrps;
        this.nxtMeetDate = nxtMeetDate;
        this.outstandingBal = outstandingBal;
        this.rcreTime = rcreTime;
        this.rcreUserId = rcreUserId;
        this.savingAccounts = savingAccounts;
        this.savingsAmt = savingsAmt;
        this.solId = solId;
    }
    public GroupsTable(String bankId, String branchName, String countryCode, String delFlg, Date firstMeetDate, Date formationDate, String gpChair, String gpRegion, String gpSecretary, String gpStatus, String gpStatusCode, String gpTreasurer, String groupAddress, String groupCenter, String groupCode, double groupLoans, String groupName, String groupPhone, String groupVillage, String grpMgrId, String grpRegNo, Date lchgDate, String lchgUserId, int loanAccounts, int maxAllowedMembers, int maxAllowedSubGrps, String meetFrequency, String meetPlace, String meetTime, int noOfMembers, int noOfSubGrps, Date nxtMeetDate, double outstandingBal, Date rcreTime, String rcreUserId, int savingAccounts, double savingsAmt, int solId) {
       this.bankId = bankId;
       this.branchName = branchName;
       this.countryCode = countryCode;
       this.delFlg = delFlg;
       this.firstMeetDate = firstMeetDate;
       this.formationDate = formationDate;
       this.gpChair = gpChair;
       this.gpRegion = gpRegion;
       this.gpSecretary = gpSecretary;
       this.gpStatus = gpStatus;
       this.gpStatusCode = gpStatusCode;
       this.gpTreasurer = gpTreasurer;
       this.groupAddress = groupAddress;
       this.groupCenter = groupCenter;
       this.groupCode = groupCode;
       this.groupLoans = groupLoans;
       this.groupName = groupName;
       this.groupPhone = groupPhone;
       this.groupVillage = groupVillage;
       this.grpMgrId = grpMgrId;
       this.grpRegNo = grpRegNo;
       this.lchgDate = lchgDate;
       this.lchgUserId = lchgUserId;
       this.loanAccounts = loanAccounts;
       this.maxAllowedMembers = maxAllowedMembers;
       this.maxAllowedSubGrps = maxAllowedSubGrps;
       this.meetFrequency = meetFrequency;
       this.meetPlace = meetPlace;
       this.meetTime = meetTime;
       this.noOfMembers = noOfMembers;
       this.noOfSubGrps = noOfSubGrps;
       this.nxtMeetDate = nxtMeetDate;
       this.outstandingBal = outstandingBal;
       this.rcreTime = rcreTime;
       this.rcreUserId = rcreUserId;
       this.savingAccounts = savingAccounts;
       this.savingsAmt = savingsAmt;
       this.solId = solId;
    }
   
     @Id @GeneratedValue

    
    @Column(name="GROUP_ID", unique=true, nullable=false, precision=10, scale=0)
    public int getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(int groupId) {
        this.groupId = groupId;
    }

    
    @Column(name="BANK_ID", nullable=false, length=8)
    public String getBankId() {
        return this.bankId;
    }
    
    public void setBankId(String bankId) {
        this.bankId = bankId;
    }

    
    @Column(name="BRANCH_NAME", nullable=false, length=50)
    public String getBranchName() {
        return this.branchName;
    }
    
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

    
    @Column(name="COUNTRY_CODE", nullable=false, length=2)
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    
    @Column(name="DEL_FLG", nullable=false, length=1)
    public String getDelFlg() {
        return this.delFlg;
    }
    
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FIRST_MEET_DATE", nullable=false, length=7)
    public Date getFirstMeetDate() {
        return this.firstMeetDate;
    }
    
    public void setFirstMeetDate(Date firstMeetDate) {
        this.firstMeetDate = firstMeetDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FORMATION_DATE", nullable=false, length=7)
    public Date getFormationDate() {
        return this.formationDate;
    }
    
    public void setFormationDate(Date formationDate) {
        this.formationDate = formationDate;
    }

    
    @Column(name="GP_CHAIR", length=50)
    public String getGpChair() {
        return this.gpChair;
    }
    
    public void setGpChair(String gpChair) {
        this.gpChair = gpChair;
    }

    
    @Column(name="GP_REGION", nullable=false, length=50)
    public String getGpRegion() {
        return this.gpRegion;
    }
    
    public void setGpRegion(String gpRegion) {
        this.gpRegion = gpRegion;
    }

    
    @Column(name="GP_SECRETARY", length=50)
    public String getGpSecretary() {
        return this.gpSecretary;
    }
    
    public void setGpSecretary(String gpSecretary) {
        this.gpSecretary = gpSecretary;
    }

    
    @Column(name="GP_STATUS", nullable=false, length=20)
    public String getGpStatus() {
        return this.gpStatus;
    }
    
    public void setGpStatus(String gpStatus) {
        this.gpStatus = gpStatus;
    }

    
    @Column(name="GP_STATUS_CODE", nullable=false, length=20)
    public String getGpStatusCode() {
        return this.gpStatusCode;
    }
    
    public void setGpStatusCode(String gpStatusCode) {
        this.gpStatusCode = gpStatusCode;
    }

    
    @Column(name="GP_TREASURER", length=50)
    public String getGpTreasurer() {
        return this.gpTreasurer;
    }
    
    public void setGpTreasurer(String gpTreasurer) {
        this.gpTreasurer = gpTreasurer;
    }

    
    @Column(name="GROUP_ADDRESS", nullable=false, length=50)
    public String getGroupAddress() {
        return this.groupAddress;
    }
    
    public void setGroupAddress(String groupAddress) {
        this.groupAddress = groupAddress;
    }

    
    @Column(name="GROUP_CENTER", nullable=false, length=50)
    public String getGroupCenter() {
        return this.groupCenter;
    }
    
    public void setGroupCenter(String groupCenter) {
        this.groupCenter = groupCenter;
    }

    
    @Column(name="GROUP_CODE", nullable=false, length=10)
    public String getGroupCode() {
        return this.groupCode;
    }
    
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }

    
    @Column(name="GROUP_LOANS", nullable=false, precision=126, scale=0)
    public double getGroupLoans() {
        return this.groupLoans;
    }
    
    public void setGroupLoans(double groupLoans) {
        this.groupLoans = groupLoans;
    }

    
    @Column(name="GROUP_NAME", nullable=false, length=50)
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    
    @Column(name="GROUP_PHONE", nullable=false, length=20)
    public String getGroupPhone() {
        return this.groupPhone;
    }
    
    public void setGroupPhone(String groupPhone) {
        this.groupPhone = groupPhone;
    }

    
    @Column(name="GROUP_VILLAGE", nullable=false, length=50)
    public String getGroupVillage() {
        return this.groupVillage;
    }
    
    public void setGroupVillage(String groupVillage) {
        this.groupVillage = groupVillage;
    }

    
    @Column(name="GRP_MGR_ID", nullable=false, length=30)
    public String getGrpMgrId() {
        return this.grpMgrId;
    }
    
    public void setGrpMgrId(String grpMgrId) {
        this.grpMgrId = grpMgrId;
    }

    
    @Column(name="GRP_REG_NO", nullable=false, length=30)
    public String getGrpRegNo() {
        return this.grpRegNo;
    }
    
    public void setGrpRegNo(String grpRegNo) {
        this.grpRegNo = grpRegNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LCHG_DATE", nullable=false, length=7)
    public Date getLchgDate() {
        return this.lchgDate;
    }
    
    public void setLchgDate(Date lchgDate) {
        this.lchgDate = lchgDate;
    }

    
    @Column(name="LCHG_USER_ID", nullable=false, length=30)
    public String getLchgUserId() {
        return this.lchgUserId;
    }
    
    public void setLchgUserId(String lchgUserId) {
        this.lchgUserId = lchgUserId;
    }

    
    @Column(name="LOAN_ACCOUNTS", nullable=false, precision=10, scale=0)
    public int getLoanAccounts() {
        return this.loanAccounts;
    }
    
    public void setLoanAccounts(int loanAccounts) {
        this.loanAccounts = loanAccounts;
    }

    
    @Column(name="MAX_ALLOWED_MEMBERS", nullable=false, precision=10, scale=0)
    public int getMaxAllowedMembers() {
        return this.maxAllowedMembers;
    }
    
    public void setMaxAllowedMembers(int maxAllowedMembers) {
        this.maxAllowedMembers = maxAllowedMembers;
    }

    
    @Column(name="MAX_ALLOWED_SUB_GRPS", nullable=false, precision=10, scale=0)
    public int getMaxAllowedSubGrps() {
        return this.maxAllowedSubGrps;
    }
    
    public void setMaxAllowedSubGrps(int maxAllowedSubGrps) {
        this.maxAllowedSubGrps = maxAllowedSubGrps;
    }

    
    @Column(name="MEET_FREQUENCY", nullable=false, length=10)
    public String getMeetFrequency() {
        return this.meetFrequency;
    }
    
    public void setMeetFrequency(String meetFrequency) {
        this.meetFrequency = meetFrequency;
    }

    
    @Column(name="MEET_PLACE", nullable=false, length=50)
    public String getMeetPlace() {
        return this.meetPlace;
    }
    
    public void setMeetPlace(String meetPlace) {
        this.meetPlace = meetPlace;
    }

    
    @Column(name="MEET_TIME", length=20)
    public String getMeetTime() {
        return this.meetTime;
    }
    
    public void setMeetTime(String meetTime) {
        this.meetTime = meetTime;
    }

    
    @Column(name="NO_OF_MEMBERS", nullable=false, precision=10, scale=0)
    public int getNoOfMembers() {
        return this.noOfMembers;
    }
    
    public void setNoOfMembers(int noOfMembers) {
        this.noOfMembers = noOfMembers;
    }

    
    @Column(name="NO_OF_SUB_GRPS", nullable=false, precision=10, scale=0)
    public int getNoOfSubGrps() {
        return this.noOfSubGrps;
    }
    
    public void setNoOfSubGrps(int noOfSubGrps) {
        this.noOfSubGrps = noOfSubGrps;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NXT_MEET_DATE", nullable=false, length=7)
    public Date getNxtMeetDate() {
        return this.nxtMeetDate;
    }
    
    public void setNxtMeetDate(Date nxtMeetDate) {
        this.nxtMeetDate = nxtMeetDate;
    }

    
    @Column(name="OUTSTANDING_BAL", nullable=false, precision=126, scale=0)
    public double getOutstandingBal() {
        return this.outstandingBal;
    }
    
    public void setOutstandingBal(double outstandingBal) {
        this.outstandingBal = outstandingBal;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RCRE_TIME", nullable=false, length=7)
    public Date getRcreTime() {
        return this.rcreTime;
    }
    
    public void setRcreTime(Date rcreTime) {
        this.rcreTime = rcreTime;
    }

    
    @Column(name="RCRE_USER_ID", nullable=false, length=30)
    public String getRcreUserId() {
        return this.rcreUserId;
    }
    
    public void setRcreUserId(String rcreUserId) {
        this.rcreUserId = rcreUserId;
    }

    
    @Column(name="SAVING_ACCOUNTS", nullable=false, precision=10, scale=0)
    public int getSavingAccounts() {
        return this.savingAccounts;
    }
    
    public void setSavingAccounts(int savingAccounts) {
        this.savingAccounts = savingAccounts;
    }

    
    @Column(name="SAVINGS_AMT", nullable=false, precision=126, scale=0)
    public double getSavingsAmt() {
        return this.savingsAmt;
    }
    
    public void setSavingsAmt(double savingsAmt) {
        this.savingsAmt = savingsAmt;
    }

    
    @Column(name="SOL_ID", nullable=false, precision=10, scale=0)
    public int getSolId() {
        return this.solId;
    }
    
    public void setSolId(int solId) {
        this.solId = solId;
    }




}


