package com.orig.gls.jpa;
// Generated May 25, 2016 10:46:27 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LaRepShdlTable generated by hbm2java
 */
@Entity
@Table(name="LA_REP_SHDL_TABLE"
    ,schema="GLS"
)
public class LaRepShdlTable  implements java.io.Serializable {


     private int shdlId;
     private int acid;
     private String bankId;
     private String delFlg;
     private String entityCreFlg;
     private double flowAmt;
     private Date flowStartDate;
     private Date lchgTime;
     private String lchgUserId;
     private Date nextDmdDate;
     private int numOfFlows;
     private Date rcreTime;
     private String rcreUserId;
     private int solId;

    public LaRepShdlTable() {
    }

    public LaRepShdlTable(int shdlId, int acid, String bankId, String delFlg, String entityCreFlg, double flowAmt, Date flowStartDate, Date lchgTime, String lchgUserId, Date nextDmdDate, int numOfFlows, Date rcreTime, String rcreUserId, int solId) {
       this.shdlId = shdlId;
       this.acid = acid;
       this.bankId = bankId;
       this.delFlg = delFlg;
       this.entityCreFlg = entityCreFlg;
       this.flowAmt = flowAmt;
       this.flowStartDate = flowStartDate;
       this.lchgTime = lchgTime;
       this.lchgUserId = lchgUserId;
       this.nextDmdDate = nextDmdDate;
       this.numOfFlows = numOfFlows;
       this.rcreTime = rcreTime;
       this.rcreUserId = rcreUserId;
       this.solId = solId;
    }
   
     @Id 

    
    @Column(name="SHDL_ID", unique=true, nullable=false, precision=10, scale=0)
    public int getShdlId() {
        return this.shdlId;
    }
    
    public void setShdlId(int shdlId) {
        this.shdlId = shdlId;
    }

    
    @Column(name="ACID", nullable=false, precision=10, scale=0)
    public int getAcid() {
        return this.acid;
    }
    
    public void setAcid(int acid) {
        this.acid = acid;
    }

    
    @Column(name="BANK_ID", nullable=false, length=8)
    public String getBankId() {
        return this.bankId;
    }
    
    public void setBankId(String bankId) {
        this.bankId = bankId;
    }

    
    @Column(name="DEL_FLG", nullable=false, length=1)
    public String getDelFlg() {
        return this.delFlg;
    }
    
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    
    @Column(name="ENTITY_CRE_FLG", nullable=false, length=1)
    public String getEntityCreFlg() {
        return this.entityCreFlg;
    }
    
    public void setEntityCreFlg(String entityCreFlg) {
        this.entityCreFlg = entityCreFlg;
    }

    
    @Column(name="FLOW_AMT", nullable=false, precision=126, scale=0)
    public double getFlowAmt() {
        return this.flowAmt;
    }
    
    public void setFlowAmt(double flowAmt) {
        this.flowAmt = flowAmt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FLOW_START_DATE", nullable=false, length=7)
    public Date getFlowStartDate() {
        return this.flowStartDate;
    }
    
    public void setFlowStartDate(Date flowStartDate) {
        this.flowStartDate = flowStartDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LCHG_TIME", nullable=false, length=7)
    public Date getLchgTime() {
        return this.lchgTime;
    }
    
    public void setLchgTime(Date lchgTime) {
        this.lchgTime = lchgTime;
    }

    
    @Column(name="LCHG_USER_ID", nullable=false, length=30)
    public String getLchgUserId() {
        return this.lchgUserId;
    }
    
    public void setLchgUserId(String lchgUserId) {
        this.lchgUserId = lchgUserId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NEXT_DMD_DATE", nullable=false, length=7)
    public Date getNextDmdDate() {
        return this.nextDmdDate;
    }
    
    public void setNextDmdDate(Date nextDmdDate) {
        this.nextDmdDate = nextDmdDate;
    }

    
    @Column(name="NUM_OF_FLOWS", nullable=false, precision=10, scale=0)
    public int getNumOfFlows() {
        return this.numOfFlows;
    }
    
    public void setNumOfFlows(int numOfFlows) {
        this.numOfFlows = numOfFlows;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RCRE_TIME", nullable=false, length=7)
    public Date getRcreTime() {
        return this.rcreTime;
    }
    
    public void setRcreTime(Date rcreTime) {
        this.rcreTime = rcreTime;
    }

    
    @Column(name="RCRE_USER_ID", nullable=false, length=30)
    public String getRcreUserId() {
        return this.rcreUserId;
    }
    
    public void setRcreUserId(String rcreUserId) {
        this.rcreUserId = rcreUserId;
    }

    
    @Column(name="SOL_ID", nullable=false, precision=10, scale=0)
    public int getSolId() {
        return this.solId;
    }
    
    public void setSolId(int solId) {
        this.solId = solId;
    }




}


