package com.orig.gls.jpa;
// Generated May 25, 2016 10:46:27 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LaTranDetailTable generated by hbm2java
 */
@Entity
@Table(name="LA_TRAN_DETAIL_TABLE"
    ,schema="GLS"
)
public class LaTranDetailTable  implements java.io.Serializable {


     private int tranId;
     private int acid;
     private String bankId;
     private String delFlg;
     private Date dmdDate;
     private int dmdId;
     private String entityCreFlg;
     private double flowAmt;
     private String flowId;
     private Date glDate;
     private Date lchgTime;
     private String lchgUserId;
     private Date rcreTime;
     private String rcreUserId;
     private Date tranDate;
     private Date valueDate;

    public LaTranDetailTable() {
    }

    public LaTranDetailTable(int tranId, int acid, String bankId, String delFlg, Date dmdDate, int dmdId, String entityCreFlg, double flowAmt, String flowId, Date glDate, Date lchgTime, String lchgUserId, Date rcreTime, String rcreUserId, Date tranDate, Date valueDate) {
       this.tranId = tranId;
       this.acid = acid;
       this.bankId = bankId;
       this.delFlg = delFlg;
       this.dmdDate = dmdDate;
       this.dmdId = dmdId;
       this.entityCreFlg = entityCreFlg;
       this.flowAmt = flowAmt;
       this.flowId = flowId;
       this.glDate = glDate;
       this.lchgTime = lchgTime;
       this.lchgUserId = lchgUserId;
       this.rcreTime = rcreTime;
       this.rcreUserId = rcreUserId;
       this.tranDate = tranDate;
       this.valueDate = valueDate;
    }
   
     @Id 

    
    @Column(name="TRAN_ID", unique=true, nullable=false, precision=10, scale=0)
    public int getTranId() {
        return this.tranId;
    }
    
    public void setTranId(int tranId) {
        this.tranId = tranId;
    }

    
    @Column(name="ACID", nullable=false, precision=10, scale=0)
    public int getAcid() {
        return this.acid;
    }
    
    public void setAcid(int acid) {
        this.acid = acid;
    }

    
    @Column(name="BANK_ID", nullable=false, length=8)
    public String getBankId() {
        return this.bankId;
    }
    
    public void setBankId(String bankId) {
        this.bankId = bankId;
    }

    
    @Column(name="DEL_FLG", nullable=false, length=1)
    public String getDelFlg() {
        return this.delFlg;
    }
    
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DMD_DATE", nullable=false, length=7)
    public Date getDmdDate() {
        return this.dmdDate;
    }
    
    public void setDmdDate(Date dmdDate) {
        this.dmdDate = dmdDate;
    }

    
    @Column(name="DMD_ID", nullable=false, precision=10, scale=0)
    public int getDmdId() {
        return this.dmdId;
    }
    
    public void setDmdId(int dmdId) {
        this.dmdId = dmdId;
    }

    
    @Column(name="ENTITY_CRE_FLG", nullable=false, length=1)
    public String getEntityCreFlg() {
        return this.entityCreFlg;
    }
    
    public void setEntityCreFlg(String entityCreFlg) {
        this.entityCreFlg = entityCreFlg;
    }

    
    @Column(name="FLOW_AMT", nullable=false, precision=126, scale=0)
    public double getFlowAmt() {
        return this.flowAmt;
    }
    
    public void setFlowAmt(double flowAmt) {
        this.flowAmt = flowAmt;
    }

    
    @Column(name="FLOW_ID", nullable=false, length=5)
    public String getFlowId() {
        return this.flowId;
    }
    
    public void setFlowId(String flowId) {
        this.flowId = flowId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="GL_DATE", nullable=false, length=7)
    public Date getGlDate() {
        return this.glDate;
    }
    
    public void setGlDate(Date glDate) {
        this.glDate = glDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LCHG_TIME", nullable=false, length=7)
    public Date getLchgTime() {
        return this.lchgTime;
    }
    
    public void setLchgTime(Date lchgTime) {
        this.lchgTime = lchgTime;
    }

    
    @Column(name="LCHG_USER_ID", nullable=false, length=30)
    public String getLchgUserId() {
        return this.lchgUserId;
    }
    
    public void setLchgUserId(String lchgUserId) {
        this.lchgUserId = lchgUserId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RCRE_TIME", nullable=false, length=7)
    public Date getRcreTime() {
        return this.rcreTime;
    }
    
    public void setRcreTime(Date rcreTime) {
        this.rcreTime = rcreTime;
    }

    
    @Column(name="RCRE_USER_ID", nullable=false, length=30)
    public String getRcreUserId() {
        return this.rcreUserId;
    }
    
    public void setRcreUserId(String rcreUserId) {
        this.rcreUserId = rcreUserId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TRAN_DATE", nullable=false, length=7)
    public Date getTranDate() {
        return this.tranDate;
    }
    
    public void setTranDate(Date tranDate) {
        this.tranDate = tranDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VALUE_DATE", nullable=false, length=7)
    public Date getValueDate() {
        return this.valueDate;
    }
    
    public void setValueDate(Date valueDate) {
        this.valueDate = valueDate;
    }




}


