package com.orig.gls.jpa;
// Generated May 25, 2016 10:46:27 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ServiceOutletTableMod generated by hbm2java
 */
@Entity
@Table(name="SERVICE_OUTLET_TABLE_MOD"
    ,schema="GLS"
)
public class ServiceOutletTableMod  implements java.io.Serializable {


     private int modId;
     private String addr1;
     private String bankId;
     private String cntryCode;
     private String delFlg;
     private String homeCrncyCode;
     private Date lchgTime;
     private String lchgUserId;
     private Date rcreTime;
     private String rcreUserId;
     private String regionCode;
     private Date solBodDate;
     private Date solClsDate;
     private String solClsFlg;
     private String solDesc;
     private String solEodStatus;
     private String solId;

    public ServiceOutletTableMod() {
    }

    public ServiceOutletTableMod(int modId, String addr1, String bankId, String cntryCode, String delFlg, String homeCrncyCode, Date lchgTime, String lchgUserId, Date rcreTime, String rcreUserId, String regionCode, Date solBodDate, Date solClsDate, String solClsFlg, String solDesc, String solEodStatus, String solId) {
       this.modId = modId;
       this.addr1 = addr1;
       this.bankId = bankId;
       this.cntryCode = cntryCode;
       this.delFlg = delFlg;
       this.homeCrncyCode = homeCrncyCode;
       this.lchgTime = lchgTime;
       this.lchgUserId = lchgUserId;
       this.rcreTime = rcreTime;
       this.rcreUserId = rcreUserId;
       this.regionCode = regionCode;
       this.solBodDate = solBodDate;
       this.solClsDate = solClsDate;
       this.solClsFlg = solClsFlg;
       this.solDesc = solDesc;
       this.solEodStatus = solEodStatus;
       this.solId = solId;
    }
   
     @Id 

    
    @Column(name="MOD_ID", unique=true, nullable=false, precision=10, scale=0)
    public int getModId() {
        return this.modId;
    }
    
    public void setModId(int modId) {
        this.modId = modId;
    }

    
    @Column(name="ADDR_1", nullable=false, length=45)
    public String getAddr1() {
        return this.addr1;
    }
    
    public void setAddr1(String addr1) {
        this.addr1 = addr1;
    }

    
    @Column(name="BANK_ID", nullable=false, length=8)
    public String getBankId() {
        return this.bankId;
    }
    
    public void setBankId(String bankId) {
        this.bankId = bankId;
    }

    
    @Column(name="CNTRY_CODE", nullable=false, length=5)
    public String getCntryCode() {
        return this.cntryCode;
    }
    
    public void setCntryCode(String cntryCode) {
        this.cntryCode = cntryCode;
    }

    
    @Column(name="DEL_FLG", nullable=false, length=1)
    public String getDelFlg() {
        return this.delFlg;
    }
    
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    
    @Column(name="HOME_CRNCY_CODE", nullable=false, length=3)
    public String getHomeCrncyCode() {
        return this.homeCrncyCode;
    }
    
    public void setHomeCrncyCode(String homeCrncyCode) {
        this.homeCrncyCode = homeCrncyCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LCHG_TIME", nullable=false, length=7)
    public Date getLchgTime() {
        return this.lchgTime;
    }
    
    public void setLchgTime(Date lchgTime) {
        this.lchgTime = lchgTime;
    }

    
    @Column(name="LCHG_USER_ID", nullable=false, length=30)
    public String getLchgUserId() {
        return this.lchgUserId;
    }
    
    public void setLchgUserId(String lchgUserId) {
        this.lchgUserId = lchgUserId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RCRE_TIME", nullable=false, length=7)
    public Date getRcreTime() {
        return this.rcreTime;
    }
    
    public void setRcreTime(Date rcreTime) {
        this.rcreTime = rcreTime;
    }

    
    @Column(name="RCRE_USER_ID", nullable=false, length=30)
    public String getRcreUserId() {
        return this.rcreUserId;
    }
    
    public void setRcreUserId(String rcreUserId) {
        this.rcreUserId = rcreUserId;
    }

    
    @Column(name="REGION_CODE", nullable=false, length=30)
    public String getRegionCode() {
        return this.regionCode;
    }
    
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SOL_BOD_DATE", nullable=false, length=7)
    public Date getSolBodDate() {
        return this.solBodDate;
    }
    
    public void setSolBodDate(Date solBodDate) {
        this.solBodDate = solBodDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SOL_CLS_DATE", nullable=false, length=7)
    public Date getSolClsDate() {
        return this.solClsDate;
    }
    
    public void setSolClsDate(Date solClsDate) {
        this.solClsDate = solClsDate;
    }

    
    @Column(name="SOL_CLS_FLG", nullable=false, length=1)
    public String getSolClsFlg() {
        return this.solClsFlg;
    }
    
    public void setSolClsFlg(String solClsFlg) {
        this.solClsFlg = solClsFlg;
    }

    
    @Column(name="SOL_DESC", nullable=false, length=132)
    public String getSolDesc() {
        return this.solDesc;
    }
    
    public void setSolDesc(String solDesc) {
        this.solDesc = solDesc;
    }

    
    @Column(name="SOL_EOD_STATUS", nullable=false, length=1)
    public String getSolEodStatus() {
        return this.solEodStatus;
    }
    
    public void setSolEodStatus(String solEodStatus) {
        this.solEodStatus = solEodStatus;
    }

    
    @Column(name="SOL_ID", nullable=false, precision=10, scale=0)
    public String getSolId() {
        return this.solId;
    }
    
    public void setSolId(String solId) {
        this.solId = solId;
    }




}


