package com.orig.gls.jpa;
// Generated May 25, 2016 10:46:27 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SolGroupControlTable generated by hbm2java
 */
@Entity
@Table(name="SOL_GROUP_CONTROL_TABLE"
    ,schema="GLS"
)
public class SolGroupControlTable  implements java.io.Serializable {


     private int solGroupId;
     private String bankId;
     private Date dbStatDate;
     private Date dcClsDate;
     private String dcClsFlg;
     private int defNumOfDaysInMth;
     private String delFlg;
     private String groupDesc;
     private String homeCntryCode;
     private String homeCrncyCode;
     private Date lchgTime;
     private String lchgUserId;
     private int numOfBackDaysAllowed;
     private int numOfFutureDaysAllowed;
     private Date rcreTime;
     private String rcreUserId;

    public SolGroupControlTable() {
    }

    public SolGroupControlTable(String bankId, Date dbStatDate, Date dcClsDate, String dcClsFlg, int defNumOfDaysInMth, String delFlg, String groupDesc, String homeCntryCode, String homeCrncyCode, Date lchgTime, String lchgUserId, int numOfBackDaysAllowed, int numOfFutureDaysAllowed, Date rcreTime, String rcreUserId) {
       this.bankId = bankId;
       this.dbStatDate = dbStatDate;
       this.dcClsDate = dcClsDate;
       this.dcClsFlg = dcClsFlg;
       this.defNumOfDaysInMth = defNumOfDaysInMth;
       this.delFlg = delFlg;
       this.groupDesc = groupDesc;
       this.homeCntryCode = homeCntryCode;
       this.homeCrncyCode = homeCrncyCode;
       this.lchgTime = lchgTime;
       this.lchgUserId = lchgUserId;
       this.numOfBackDaysAllowed = numOfBackDaysAllowed;
       this.numOfFutureDaysAllowed = numOfFutureDaysAllowed;
       this.rcreTime = rcreTime;
       this.rcreUserId = rcreUserId;
    }
   
     @Id @GeneratedValue

    
    @Column(name="SOL_GROUP_ID", unique=true, nullable=false, precision=10, scale=0)
    public int getSolGroupId() {
        return this.solGroupId;
    }
    
    public void setSolGroupId(int solGroupId) {
        this.solGroupId = solGroupId;
    }

    
    @Column(name="BANK_ID", nullable=false, length=8)
    public String getBankId() {
        return this.bankId;
    }
    
    public void setBankId(String bankId) {
        this.bankId = bankId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DB_STAT_DATE", nullable=false, length=7)
    public Date getDbStatDate() {
        return this.dbStatDate;
    }
    
    public void setDbStatDate(Date dbStatDate) {
        this.dbStatDate = dbStatDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DC_CLS_DATE", nullable=false, length=7)
    public Date getDcClsDate() {
        return this.dcClsDate;
    }
    
    public void setDcClsDate(Date dcClsDate) {
        this.dcClsDate = dcClsDate;
    }

    
    @Column(name="DC_CLS_FLG", nullable=false, length=1)
    public String getDcClsFlg() {
        return this.dcClsFlg;
    }
    
    public void setDcClsFlg(String dcClsFlg) {
        this.dcClsFlg = dcClsFlg;
    }

    
    @Column(name="DEF_NUM_OF_DAYS_IN_MTH", nullable=false, precision=10, scale=0)
    public int getDefNumOfDaysInMth() {
        return this.defNumOfDaysInMth;
    }
    
    public void setDefNumOfDaysInMth(int defNumOfDaysInMth) {
        this.defNumOfDaysInMth = defNumOfDaysInMth;
    }

    
    @Column(name="DEL_FLG", nullable=false, length=1)
    public String getDelFlg() {
        return this.delFlg;
    }
    
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    
    @Column(name="GROUP_DESC", nullable=false, length=40)
    public String getGroupDesc() {
        return this.groupDesc;
    }
    
    public void setGroupDesc(String groupDesc) {
        this.groupDesc = groupDesc;
    }

    
    @Column(name="HOME_CNTRY_CODE", nullable=false, length=5)
    public String getHomeCntryCode() {
        return this.homeCntryCode;
    }
    
    public void setHomeCntryCode(String homeCntryCode) {
        this.homeCntryCode = homeCntryCode;
    }

    
    @Column(name="HOME_CRNCY_CODE", nullable=false, length=3)
    public String getHomeCrncyCode() {
        return this.homeCrncyCode;
    }
    
    public void setHomeCrncyCode(String homeCrncyCode) {
        this.homeCrncyCode = homeCrncyCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LCHG_TIME", nullable=false, length=7)
    public Date getLchgTime() {
        return this.lchgTime;
    }
    
    public void setLchgTime(Date lchgTime) {
        this.lchgTime = lchgTime;
    }

    
    @Column(name="LCHG_USER_ID", nullable=false, length=30)
    public String getLchgUserId() {
        return this.lchgUserId;
    }
    
    public void setLchgUserId(String lchgUserId) {
        this.lchgUserId = lchgUserId;
    }

    
    @Column(name="NUM_OF_BACK_DAYS_ALLOWED", nullable=false, precision=10, scale=0)
    public int getNumOfBackDaysAllowed() {
        return this.numOfBackDaysAllowed;
    }
    
    public void setNumOfBackDaysAllowed(int numOfBackDaysAllowed) {
        this.numOfBackDaysAllowed = numOfBackDaysAllowed;
    }

    
    @Column(name="NUM_OF_FUTURE_DAYS_ALLOWED", nullable=false, precision=10, scale=0)
    public int getNumOfFutureDaysAllowed() {
        return this.numOfFutureDaysAllowed;
    }
    
    public void setNumOfFutureDaysAllowed(int numOfFutureDaysAllowed) {
        this.numOfFutureDaysAllowed = numOfFutureDaysAllowed;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RCRE_TIME", nullable=false, length=7)
    public Date getRcreTime() {
        return this.rcreTime;
    }
    
    public void setRcreTime(Date rcreTime) {
        this.rcreTime = rcreTime;
    }

    
    @Column(name="RCRE_USER_ID", nullable=false, length=30)
    public String getRcreUserId() {
        return this.rcreUserId;
    }
    
    public void setRcreUserId(String rcreUserId) {
        this.rcreUserId = rcreUserId;
    }




}


