package com.orig.gls.jpa;
// Generated May 25, 2016 10:46:27 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserCredsTbl generated by hbm2java
 */
@Entity
@Table(name = "USER_CREDS_TBL", schema = "GLS"
)
public class UserCredsTbl implements java.io.Serializable {

    private int userId;
    private Date acctExpyDate;
    private int acctInactiveDays;
    private Date disabledFromDate;
    private Date disabledUptoDate;
    private String empId;
    private Date lastAccessTime;
    private String newUserFlg;
    private int numPwdAttempts;
    private int numPwdHistory;
    private Date pwExpyDate;
    private String pwdHistory;
    private int roleId;
    private String userName;
    private String userPw;
    private String userStatus;
    private String lchgUserId;

    public UserCredsTbl() {
    }

    public UserCredsTbl(Date acctExpyDate, int acctInactiveDays, Date disabledFromDate, Date disabledUptoDate, Date lastAccessTime, String newUserFlg, int numPwdAttempts, int numPwdHistory, Date pwExpyDate, String pwdHistory, int roleId, String userName, String userPw, String userStatus, String lchgUserId) {
        this.acctExpyDate = acctExpyDate;
        this.acctInactiveDays = acctInactiveDays;
        this.disabledFromDate = disabledFromDate;
        this.disabledUptoDate = disabledUptoDate;
        this.lastAccessTime = lastAccessTime;
        this.newUserFlg = newUserFlg;
        this.numPwdAttempts = numPwdAttempts;
        this.numPwdHistory = numPwdHistory;
        this.pwExpyDate = pwExpyDate;
        this.pwdHistory = pwdHistory;
        this.roleId = roleId;
        this.userName = userName;
        this.userPw = userPw;
        this.userStatus = userStatus;
        this.lchgUserId = lchgUserId;
    }

    public UserCredsTbl(Date acctExpyDate, int acctInactiveDays, Date disabledFromDate, Date disabledUptoDate, String empId, Date lastAccessTime, String newUserFlg, int numPwdAttempts, int numPwdHistory, Date pwExpyDate, String pwdHistory, int roleId, String userName, String userPw, String userStatus) {
        this.acctExpyDate = acctExpyDate;
        this.acctInactiveDays = acctInactiveDays;
        this.disabledFromDate = disabledFromDate;
        this.disabledUptoDate = disabledUptoDate;
        this.empId = empId;
        this.lastAccessTime = lastAccessTime;
        this.newUserFlg = newUserFlg;
        this.numPwdAttempts = numPwdAttempts;
        this.numPwdHistory = numPwdHistory;
        this.pwExpyDate = pwExpyDate;
        this.pwdHistory = pwdHistory;
        this.roleId = roleId;
        this.userName = userName;
        this.userPw = userPw;
        this.userStatus = userStatus;
    }

    @Id
    @GeneratedValue

    @Column(name = "USER_ID", unique = true, nullable = false, precision = 10, scale = 0)
    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "ACCT_EXPY_DATE", nullable = false, length = 7)
    public Date getAcctExpyDate() {
        return this.acctExpyDate;
    }

    public void setAcctExpyDate(Date acctExpyDate) {
        this.acctExpyDate = acctExpyDate;
    }

    @Column(name = "ACCT_INACTIVE_DAYS", nullable = false, precision = 10, scale = 0)
    public int getAcctInactiveDays() {
        return this.acctInactiveDays;
    }

    public void setAcctInactiveDays(int acctInactiveDays) {
        this.acctInactiveDays = acctInactiveDays;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DISABLED_FROM_DATE", nullable = false, length = 7)
    public Date getDisabledFromDate() {
        return this.disabledFromDate;
    }

    public void setDisabledFromDate(Date disabledFromDate) {
        this.disabledFromDate = disabledFromDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DISABLED_UPTO_DATE", nullable = false, length = 7)
    public Date getDisabledUptoDate() {
        return this.disabledUptoDate;
    }

    public void setDisabledUptoDate(Date disabledUptoDate) {
        this.disabledUptoDate = disabledUptoDate;
    }

    @Column(name = "EMP_ID", length = 20)
    public String getEmpId() {
        return this.empId;
    }

    public void setEmpId(String empId) {
        this.empId = empId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "LAST_ACCESS_TIME", nullable = false, length = 7)
    public Date getLastAccessTime() {
        return this.lastAccessTime;
    }

    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }

    @Column(name = "NEW_USER_FLG", nullable = false, length = 1)
    public String getNewUserFlg() {
        return this.newUserFlg;
    }

    public void setNewUserFlg(String newUserFlg) {
        this.newUserFlg = newUserFlg;
    }

    @Column(name = "NUM_PWD_ATTEMPTS", nullable = false, precision = 10, scale = 0)
    public int getNumPwdAttempts() {
        return this.numPwdAttempts;
    }

    public void setNumPwdAttempts(int numPwdAttempts) {
        this.numPwdAttempts = numPwdAttempts;
    }

    @Column(name = "NUM_PWD_HISTORY", nullable = false, precision = 10, scale = 0)
    public int getNumPwdHistory() {
        return this.numPwdHistory;
    }

    public void setNumPwdHistory(int numPwdHistory) {
        this.numPwdHistory = numPwdHistory;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "PW_EXPY_DATE", nullable = false, length = 7)
    public Date getPwExpyDate() {
        return this.pwExpyDate;
    }

    public void setPwExpyDate(Date pwExpyDate) {
        this.pwExpyDate = pwExpyDate;
    }

    @Column(name = "PWD_HISTORY", nullable = false, length = 3072)
    public String getPwdHistory() {
        return this.pwdHistory;
    }

    public void setPwdHistory(String pwdHistory) {
        this.pwdHistory = pwdHistory;
    }

    @Column(name = "ROLE_ID", nullable = false, precision = 10, scale = 0)
    public int getRoleId() {
        return this.roleId;
    }

    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }

    @Column(name = "USER_NAME", nullable = false, length = 30)
    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Column(name = "USER_PW", nullable = false, length = 100)
    public String getUserPw() {
        return this.userPw;
    }

    public void setUserPw(String userPw) {
        this.userPw = userPw;
    }

    @Column(name = "USER_STATUS", nullable = false, length = 2)
    public String getUserStatus() {
        return this.userStatus;
    }

    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus;
    }

    @Column(name = "LCHG_USER_ID", length = 30)
    public String getLchgUserId() {
        return lchgUserId;
    }

    public void setLchgUserId(String lchgUserId) {
        this.lchgUserId = lchgUserId;
    }

}
